/**
 * The cross-platform UI seam. The web and native adapters own rendering, but
 * they consume the same semantic class contract so a visual change has one
 * named home instead of two unrelated style systems.
 */
export const uiClasses = {
  root: 'og-root',
  screen: 'og-screen',
  screenStatic: 'og-screen-static',
  header: 'og-header',
  headerCompact: 'og-header-compact',
  headerRow: 'og-header-row',
  headerRowCompact: 'og-header-row-compact',
  title: 'og-title',
  compactTitle: 'og-compact-title',
  subtitle: 'og-subtitle',
  iconButton: 'og-icon-button',
  card: 'og-card',
  cardFlat: 'og-card-flat',
  cardItem: 'og-card-item',
  cardTitle: 'og-card-title',
  body: 'og-body',
  small: 'og-small',
  label: 'og-label',
  button: 'og-button',
  buttonCompact: 'og-button-compact',
  buttonText: 'og-button-text',
  buttonTextCompact: 'og-button-text-compact',
  row: 'og-row',
  between: 'og-between',
  divider: 'og-divider',
  input: 'og-input',
  section: 'og-section',
  sectionHeader: 'og-section-header',
  fieldGroup: 'og-field-group',
  stat: 'og-stat',
  statValue: 'og-stat-value',
  listRow: 'og-list-row',
  itemRow: 'og-item-row',
  listIcon: 'og-list-icon',
  listMain: 'og-list-main',
  listTitle: 'og-list-title',
  itemTitle: 'og-item-title',
  listSubtitle: 'og-list-subtitle',
  chip: 'og-chip',
  chipText: 'og-chip-text',
  toggle: 'og-toggle',
  toggleOn: 'og-toggle-on',
  toggleKnob: 'og-toggle-knob',
  segmented: 'og-segmented',
  segmentedOption: 'og-segmented-option',
  segmentedSelected: 'og-segmented-selected',
  segmentedText: 'og-segmented-text',
  segmentedTextSelected: 'og-segmented-text-selected',
  empty: 'og-empty',
  progress: 'og-progress',
  progressFill: 'og-progress-fill',
  tabBar: 'og-tabbar',
  tab: 'og-tab',
  tabCenter: 'og-tab-center',
  tabCircle: 'og-tab-circle',
  tabLabel: 'og-tab-label',
  workoutMedia: 'og-workout-media',
  week: 'og-week',
  weekDay: 'og-week-day',
  weekLabel: 'og-week-label',
  weekNumber: 'og-week-number',
  todayNumber: 'og-today-number',
  dot: 'og-dot',
  todayRow: 'og-today-row',
  rowIcon: 'og-row-icon',
  listCard: 'og-list-card',
  itemCard: 'og-item-card',
  rowSeparator: 'og-row-separator',
  tag: 'og-tag',
  tagText: 'og-tag-text',
  accentTag: 'og-accent-tag',
  accentTagText: 'og-accent-tag-text',
  miniChart: 'og-mini-chart',
  miniBar: 'og-mini-bar',
  tile: 'og-tile',
  heatmapMonths: 'og-heatmap-months',
  heatmapMonth: 'og-heatmap-month',
  heatmapBody: 'og-heatmap-body',
  heatmapDays: 'og-heatmap-days',
  heatmapDay: 'og-heatmap-day',
  heatmapGrid: 'og-heatmap-grid',
  heatmapColumn: 'og-heatmap-column',
  heatmapCell: 'og-heatmap-cell',
  heatmapLegend: 'og-heatmap-legend',
  heatmapLegendText: 'og-heatmap-legend-text',
  progressTrack: 'og-progress-track',
  activityCell: 'og-activity-cell',
  exerciseThumb: 'og-exercise-thumb',
  workoutImage: 'og-workout-image',
  setHeader: 'og-set-header',
  setHeaderText: 'og-set-header-text',
} as const

export type UIClassName = typeof uiClasses[keyof typeof uiClasses]

export function cx(...names: Array<string | false | null | undefined>): string {
  return names.filter(Boolean).join(' ')
}
